# Configuración del servidor
server.port=8080

# Configuración de MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://camiloovalle0658_db_user:WAXOLiFTEHpUrPtq@cluster0.14gtyiq.mongodb.net/?appName=Cluster0

# Configuración de CORS (para permitir peticiones desde el frontend)
# Se configura en la clase WebConfig.java
